
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    env_file:
      - .env
    # command: yarn dev  # Adicionado para iniciar a aplicação em modo de desenvolvimento
    networks:
      - my_network


  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "${DATABASE_PORT}:5432"
    restart: always
    env_file:
      - .env
    networks:
      my_network:
        ipv4_address: 172.20.0.2

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
